name: stak
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - cython
  - numpy
  - scipy
  - astropy
  - numpydoc
  - pyparsing
  - nbconvert >= 4.2.0
  - pip:
    - sphinx_automodapi
    - sphinx_rtd_theme
    - stsci_rtd_theme
